---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-auth
  namespace: flux-system
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:F/xm,iv:QeG8NlmjM9EymZJiVyYhymWQgxUBxBLL8W3H4Y5Xfwc=,tag:HFQ8bBdLYLMB/UAnUFtyag==,type:str]
  password: ENC[AES256_GCM,data:LeaaWzMbDU7um98tDAwxL/moU5PBB9MjvntaxwFKQ/zWE0tzF0OsYA==,iv:5+GTzAKhLzzrKqEnrrI7OR6idedkuZTIHgzEyBp90xs=,tag:WEttpdisOlMafq0YYk0zyA==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K09lQkFKbGtISmJWY3Ez
      bFgwUlBReHRtMjh2ai9Nd1RzRGdBZzArdHl3CmRWMGk0anZRdHl2Sk5vdE1NeEsw
      WkJ0R2VnTXJ4Lzh1bmhMMC9uSUxPOXcKLS0tIE41bzNoRTNnSURQMDBjWnFyZFBO
      Ymd5ZjNzMmVad3NpSVQwZjVGbWJhcE0KCfPqmM68WYwdZcHoixYPRrM+O6u70buX
      KWNxgJtxvB0HcpSW9XKsLAz7Qkj6Sq0016hcNsJpTHkJjlR4qVmbGg==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ29mb2VlTWUzck9JSHlv
      VUNzcW90V0t3M0Qxd3NZa3RGV2t3aWJhakJJCjFwYmlGQm11Z1YzekRoeXNFVzNV
      VVQ1T3lyUXpEMldZMng5Ukxna1ppUjgKLS0tIDZFOUlWaldkSFZUTmhHay85a3ky
      b2pMWXBwZnhwbGNZMk9tcWJHYXZZQ2sKzgSvn7p0HG151d6FHgFaaxTK004eYW0Y
      3ek2DF2wB1Vlk3BSx+SLQQahRDe5tuyRP8MaCtx0yA4S02gLr3Gdzg==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T07:42:10Z"
  mac: ENC[AES256_GCM,data:XipgH5acic1PRNFVp5fPgwLtEHGbPEJrgTueh3dpf4+FnS65q1an8n+2Ij4tJijF8RtVPV/pOcBOZt+sh0ro/O8QHzR9392TxShtFJmayeCw0uuxExOVB2HJp6Ha1Qk49ipDW7WDoSHufkq9Oz0OfMbHi8LMp+5sJlVtXQRLA2Y=,iv:4d+V4eXh/C1zFsTvVSOu5Gf6nPQOy6G9S+tY01aV0SQ=,tag:69lrNgdXs0dzMu5Xmbpf4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
