apiVersion: ENC[AES256_GCM,data:2+w=,iv:0nj3SXgvBkU+nbCFYn8YjvbPtVKgrEyT5kC4TQZ0+Jw=,tag:Ee1/RmATPxerR1u8/SDFJA==,type:str]
kind: ENC[AES256_GCM,data:QNUgW5IL,iv:UDCe8JVMH21u9DEiu+T7yIb0rdkHDKS8s0ktHjRBVB4=,tag:aOWH9R2Upzi/DRBBmDF9GQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jNHE90qasMzev7RihQ==,iv:vuR3KEO+lE3CxLUZY+0WjmuhV7stgWTHv4yZL/8fgpI=,tag:qdt0alQgc8cC+im1KVbITA==,type:str]
    namespace: ENC[AES256_GCM,data:6EK6ivl+Idibuhs=,iv:3JNm3cZV5b3ygXnzHKbQw5WYYADJJyUDBtu7bCAsZPQ=,tag:CPwyK9Z/p/wLiKk6ogdKXA==,type:str]
type: ENC[AES256_GCM,data:nxdvhczK,iv:63Ocwas+hl6boBY1xyKrLt5FmfggB7VHxbYXY7ZNMQ8=,tag:8R7ZIzNwkNjM5ipQMZb18Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:RqrA,iv:uvQzflFrqMT72lx+wDnZqejRrAT5snIrmvyA5t3Op8c=,tag:E15bMXdHD38mxQZ/VSKMZg==,type:str]
    password: ENC[AES256_GCM,data:vWmwZuZXk52f4Tq1bjWv5F9noliJWId6vEYtP/aH3h03dhBtcg5OKg==,iv:yYBMadm6ZZHPr+3z6G29+UlmBwZ5EP52n0UtBVESxKM=,tag:7BX9TqBsK6NJ50InW11GXA==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYekZMRjJIanE2N2c4OG9a
            V1BQaW9DcHpVUmJndzlacEhnbERrYUc0UWlvCmIvam5IWlM4OWllSU5rWkwyWFhx
            NnRTaWtXeW5uQ0c1ZlByQ2RiUy9DUTgKLS0tIFlPNUVJNG8vbk05MlJWVmZxQUo0
            MnZ0T2tScjlVTytEWUhOY3M2ak1iSGMKEVWr1sdNpyiDweCv8LON2qujd2XTKyA/
            V0pLZT0olgppaOLP447kM7pxI/F6I2GglyJN+G6/SxoqqTB0gbMSuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WEtrZ00zTmF4MTZtOXQ3
            U2gySjJ1NmVvZkpvK1pNeFFxYytubTJIZXhVCmhTaVFDUUtaTzlZWjd3NTkzeW5o
            VTIvOHRXamZwcnFLL2hVaVY2RUlJRWsKLS0tIDdiaTZIMDBnV3U4c1NUR3RXNEZH
            SFJJY2wzR0JnakNIRU0vaEhvTGppUFkK62ASNjbJnt63spAEBp9cCRSxM0chz44e
            +/8Ge1lXFs0eY78Wo2LqiCsbX7dPvOQjWUgYRwGik698N3NgBi6maA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T22:42:16Z"
    mac: ENC[AES256_GCM,data:/sFG0YHSbMpM/uBuUTauyiEKXTnAJS6yh5xL1NGr/8S81dhfF75z1X4iRKgv7w63bTlOIcO20M5VdeBh90Y3n7ItPKrozwjna0YYGiK5s9APr3nxFouReg0F1dxUyyiuOtuC1QoG0ECc/xY5xdipHuXc5QnX6SN1ovzrYJHmixk=,iv:qFWXfh0Q75hdcPi9Gfp7V4RLjx4jIXslIXEsTc7ou2Q=,tag:gYt+M+0eEI6irzv4nSqwpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
