apiVersion: v1
kind: Secret
metadata:
    name: flux-git-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VTCX,iv:ihZSdFT2E3hBjaIHOuIbojpTsAz3+Jwdah7d7ADjFgE=,tag:BNFkGvs/W9o2kcjeO367Kw==,type:str]
    password: ENC[AES256_GCM,data:cig0asj6N5zw04FyKXjoxIgv4Uiws5phK5+Vbl2rE2qfRf4lK4unIA==,iv:83makFWtpPN+Z3R9KUbVqx8t/L7mPP3xvNuqrttWY1M=,tag:DrhlH4vXMC9/81zzr/QuBQ==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOXBXdVlKR2Qxc1ByeDBO
            dkEwUDhlRnRQWS85dEE1K1lCSnVxcGwzeFQ0CmF3QkF4Mkl3RkFrZERWOEFrcEhO
            WDJvRmNtVEFTNW5oS2RuSWE2QzJ4WDQKLS0tIFVZRlJSYzBRaEhpZ1NEZnl2S2tv
            eEVBR21FRk1pZjdkWVBIR2dBdVRKQ2sKODVbb63Ve0S59ZiJGKekBEnBKvNzBdBf
            f6VjD8UF/BnloSIKeBJas9hCJrgS1CJxUW2u8AMr3FYh38nq9Xgrkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL0FOaWFGYXg0d21xTzAx
            SlVCQjRLM05QaEIxOGV6Q2dQU085VlZmQ1Y4CjVuZFQzVTJOZ2lPZnhOZGE0UERS
            K0lQMUx2SlVtT3lIVUZZYUlmZmQ3dzQKLS0tIFhaQjBHeFJBRWEvaTdBL3F2akpS
            d1Q1TU5kTkNDdDQzUG5aaDlwbm05S2sK+H8z+NRv7+dgrrU4QxXLION4wO+TqVlQ
            qWt9duDcNn56bOBtkU0gBysyI6Fj9sPQwec4v+MKW8vUProRNP9I6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T16:18:35Z"
    mac: ENC[AES256_GCM,data:FHBRC3VgF3XU03U50TM1098Vs0ZpWB5z2F/wx3anhNh9NzHEuR8i/3cey1L8AxQkarOKwRpAu6H2K24E5q0jwkgry315AfIIo2B4ZrktaH46uyFFhCWHvE84JmVgLLHQIOoOYr5Iwx2c6+aRcZl5lMFQQbM0lqwcS6BOx7XyCdg=,iv:pQQmngnPmFNOPQkrWim08zYo4HiwPhoT2RoWVTE+xrA=,tag:lpEh5ob9pmVpE+XGrH9JqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
