---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-auth
  namespace: flux-system
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:BoIy,iv:X53X/8+nX5KoyXAduhCCT4gDNiOp2N6GEhSXyU630O4=,tag:HK7QVBLGUe+aB+/5gtu31Q==,type:str]
  password: ENC[AES256_GCM,data:ak+4z5/o2yh8hOgbsYAPs0IyXDgq3JeO0XlKA9SJiCufMlgOhje4QA==,iv:vhkA/qr9AeON2bULtu32LedJ4NmrnNY33WKZLaJRR3o=,tag:9Tz3C4Vrk6S8o1/SDqdOaA==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBb1lkWkh0YVVKc3o4NGVC
      ZVoyaktZVytMU1lTQ1lBYm5Ha3k4TVVSOEdnClp4bjJHRnl3bE5wT2ZLdG1LcWFn
      OXl6YU90cWhtWW1kOEZIV1UxVzJHWDAKLS0tIFBLUGlzODJxKzlxOC9YVWNyRy9o
      eGlmSWRFY3VsRm1qNXA3VTNwVk44ZVEKiM0OFKA2uIfKc4dI77/7SiNp4vXuhm3x
      TZISZ6GBJKbWGFajhT/YS7mEGY/PuyN33jhgGdqcClrrwva231l/FA==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSjJzbEl6d29sUGhZYnJP
      dEphU2VDVFM0aFBPVlpzQjFlM01NSTRDUTBnClh2cUVzaXN4Qk8wUm5pZ0RPMGpm
      Rk1la2Fod0hLbStCbkNYckVkNUdEZjQKLS0tIFkvN0ZqcXRWSHNjN1V4MkhNK2lN
      MGVqS3ZpclZXVWlhUHRQdE1EZ1N3ejgKd87jpqRyR+/Ihdn9KJmuDY170SpjpD5y
      olAyIOAQCu+elLHZ5QxBhzA8DDVIjGB5TQSeiiKgq82WGOizhK5Mcg==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T09:50:21Z"
  mac: ENC[AES256_GCM,data:DmWMgJtMvyf9hVHBGGtVY+iIA57/3Ct7EEnzRiAuguPfL5nqtw/jagMSiB/dRsC/QzHfFJND+Xt2D3xW/F8eu0bdllRanj/Y/d9OeIkicrLKSTNUkYhOIA0+n1AHGyKgK3qGfKbGWB66+QJSPnTGRSYxjsLI5kBlsM8XPMFosDo=,iv:2QvQRxHJfr9UqEBzCJaaNILrjsAFbI+cFDeKBNkwZs8=,tag:qxVjQOrdDevNtCXFpXawEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
