---
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  identity.agekey: ENC[AES256_GCM,data:cDzryYQ7/4hw0UraREcnaG8KWRmRPPaLq15x8IoqY5FLTCr8dlXLGOeunP/sNFM5GBZbdPjO9kcxfYIJy33s9xlKabKxqJKnp+s=,iv:e/ScLQCOP+crU32hBoEymBbH8mpzZY3nX4WOhjV9MdY=,tag:luwUEASfb/1iHwUw6HZ8Fg==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXakc3STZmSEU1VEZlSjY5
      QlplRytKa1F3VzdqVWROVXgvNWxYTFoyMVZFCkdnaGhtSXduRWREbnZkdUdUaWZW
      VEJ3eHVXemxSVVd0ZkZsUTB5WTJTTHMKLS0tIGhmZnJUMzZzQXF5SXNnNXNnZDVa
      YjhZU0kwYjBKL3Q5YkxsK1M1ZU80YVkK/w9xsID11onKMEWvWoEqhppO81F//yAm
      nB79pyM3Bu3y/BbrgTH8mMHk9Ld26LyUSz2xYDQEC8SBtiZQxFpQPA==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Y1doZVNRSkFQYjROQnFL
      d0FKR3ZQN1dWcFpUd3ZqYUMwMEFRcnBNc2lrClBwK2hTeVBmaEtkTHZvVW5lMjU0
      M2NRZG5sUFM4b1liZ2thdWJjYnpkc1kKLS0tIFFhNW5Bb1NnRk5YQ092RHcvRW95
      T1dSR0h3RE10aEJTL2FVcFNMV0lFYW8KKxb7RCc3oScyV5Iw4c00bU8AHIZdITDa
      bA5gE+gDS2d0JNXHZuha75w89RBTjogDWKprnHSn7qegtmKisd2qcQ==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T17:00:28Z"
  mac: ENC[AES256_GCM,data:j239FO0u7ggMW7gWv12tq/hVwVP+uXj1/r8sXn9pnJ8dsCNOKMxMRNB0yNCQceIJ/LWHzmK2GZGtPUa8i4hG7/jJZhKKG/AIkSq8fCz375dJIHcAWkEPmHFKisZKOVqQecdPhDjf7NsMTzaq7ms7eYhxDqLqf8ZgHX8P7udWIuI=,iv:S98H04YgEJSLf7f3baTfNR9QACkqXMRZvR6lHQlQrbI=,tag:z5JY9VCYiVgng64MqU142g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
