apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    identity.agekey: ENC[AES256_GCM,data:Ad35dk+0c/NDV9YQXo6kUBZGKNckzRWhXnnEgsEMI2Iy5A/WISAB4A3QBgzBqPQa4GZADX1nXrvK38RUksP+XkRgqkDfGsqOV4w=,iv:NfEPM/iGfWJMWVs3yiPp9SaxwXWugCUnNGB5ADp3eG8=,tag:IptjM+7tYBpCWxn+5hQwSg==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVmpaWUFldXMybUMrY1VZ
            S3dlNVhjMU9kdHRuSXQ5MXhIcVdFclNJL0NRCkpzSmg4VUpUcHU2ZGNDSjRod3o0
            QUtYMjk1bDFqKytISmEydldJQ1BBMUEKLS0tIGtFMU5HS2ZQcjBSNlQ1THNGbXgv
            Vy9yWkVINytEMzMvNWROWnFJQXNycUkKae+/8s/bYQ3yLPtS8blcyuVYdiAzbF4l
            Qu2scrt1rbyZO4e1h98knTSZDnc3iGZKKyAA+zSdDAZrrH7c0wn0nA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU2N5ekJ6QWdYMng5YnFm
            VDQxUE5zbGF1N0JSMHlSY0IvM1FLS3hqeGw0CjVkT3llUW5Dck5iWFlHWjIyRHFj
            SUdwT29qSjUvU2VzWGhkS0Z2dTJlL0EKLS0tIFR2bG5iUTJXRnUrV2JIU0o4RW8z
            K0JYdzdzc3JHcVBnYitPZzRxbHlGTmcKMx5fYHTrTMJFQqZnOpvk/79RzCSvCbjy
            HXQ/dHk4I/oRWw9uix8nX5ii1cRKRFCmfGRgbEf3I5YcZidzu4fCTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T16:18:48Z"
    mac: ENC[AES256_GCM,data:48lmD7SY+nx0rhAk23iOmfERlVQl9w6h5q6L0Gg3uHa7G8XLEQrp8m76hDyD+0SjTWTwc96X2qcw3J5qGUmt4yj8WAAVDk2ZveJ8qwiU2i6MLBhVpmkLJV5vNd19yJ/0un5bYUvAzOu2vXC0E2mFYzFEb16ajR5LqdBw1bdjW+I=,iv:Lqqp8sNcmQ5eTSpUkMsQ4sWYX3murQcnkf41DgmhhXA=,tag:NC++Lm2P7wEH91YIPcjXpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
