apiVersion: v1
kind: Secret
metadata:
    name: jitsi-secrets
type: Opaque
stringData:
    JITSI_CLIENT_ID: ENC[AES256_GCM,data:X5p2TUN6t+cuJnZg2mpow+Os1kQ8/6CKjV5i2bjPSVBuYqEflX3W,iv:RMO7fr9btY7MKdP0UwGKbiMSHMlWLzg9+4eB0RK1Dv8=,tag:CrG4fYsYX5XWdQyWxzTXBQ==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb2UxVnB0ZXh5MExLR3l4
            UmtoVnFrbUc0RHFISk5KakQ3VWlmV0xnaTBvCnJLSjFzQjJZRWpvVmZiaGV0TzUy
            akp3anhxSWx2SFU2T2tkdDI3c1NKNmsKLS0tIG9lNVl1bElKWkUzVEZqOENJNVEr
            c0hIN243K2U5WFpaK1JPYXdwZkUzTjAKPco33nHtcW4LHcdCFr7R42Im1vn+8JRP
            4AAwW1s4Qyp3ghmYfeITF1r432sYGYXiDGTgsoYzsD2JHfd9EEIh2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYUZKUGN5YnFwUlY1dzQ3
            N1U3YlVuc2haQXN4TFZuOGU5QWtSZ21yR0ZzClY3ajdmWUFTZVd5Q2tXK3p5UlhX
            Z0NQQlJkZVlsdm8wamRKREpWUzZrVE0KLS0tIHZFUVJDcGdHL0tHZmFPZkh0SGV6
            RE1uMGhDaS9oVmc3aytIYlBva1RFVG8KsCh2FAiltvLeW52J4tLDpri6EsE0CfkU
            aHTLqr+0jrhFwO5FGmu9y4KNKYuTeZmvLnkSIPW6qfUa53hCGuiyNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T21:59:48Z"
    mac: ENC[AES256_GCM,data:EVEPnq5XVFipx2wxoreN7oQO4RgLFrFu2VUDr7yZZR7b/2OCljQt5jhvH0FqG1XaUxJO4U8ioN7fCQjJ79z2oWqUXec1KdpluhzF7L6zqIPu7ncD+GBNLZtoQUhFxpqqH2yIDozvdVxKOhXDJC+fqZuhCEcRHmznmJgxPX7Hd0o=,iv:3oKBAS7Cxdcd1OGMTvOQ/M2gglyMPg59qK5nbbbAQvM=,tag:/1G78DJuiz8oL3xwl7NXaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
