---
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-secrets
type: Opaque
stringData:
  JWT_APP_SECRET: ENC[AES256_GCM,data:76qrq4HQgM/7u/PYWtcBrw5sw11olg1G6TQ6pPmwoq0=,iv:uQbSZhvfiveVM5spWyNUVPOPpeq7hD+SGUvr8InSYro=,tag:pCDSw8UXTIlCEkpU5YIOkA==,type:str]
  TOKEN_AUTH_URL: ENC[AES256_GCM,data:UFi6uevcyXIHLgJAej4cztHQM+roE5ghwNF1hez33jEmxu6QUFBAdIHVLo19ikgplWjkXwMmwZOm/KW4VSA5ysr3Ha7guCxEjPy/l6BjQdhvE0aw3Eie0S8vpP6LWvYhvTnwltIImHQ/gD0wJI4UVR/xivovtrEg2BrUa60854BE70bs6/7ylETQ5D/rGmX/1NHj9fVSYKWm4TZtpbdaPtG8mPTQ9KvI2TuDjdLeXnCtiEhghKcYTlOCsbMDug==,iv:RMPPmmfh1z3AExIwCLaFttCBSQUhFU2iIi8UI9kvsKU=,tag:4uPtsbGbTILd20WiDgKk5Q==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T1ZMSFNvdWVEQ2tPVmhZ
      dFhjdFArMHFDdDhJRFB0dEdoRlJJVHFFSFJBCjJMTzFRdXV0K2xUNkQya011cUNF
      U05SanNyS0d5NGlJQ29ibStLTlJtQ0kKLS0tIEdtWExxVWtNbTVJSHpza2VvcWNR
      V1JxdUE5eTlZYVBLK0IvWGc3ZVN4WU0Kq3beRaOsrEgyLEty7pg6gIBqMyBkCego
      sHfg0s26RYukxkuKJGRstIsEicvKuQXTcTj6agnyALxX2+qT1TxeEg==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdU56TGR6QldCQzhPMXpM
      OUthU3VHcEpTYmhWc3lRd2Z3MlZEenZWdnpBCk4wL05VS3BvN2JvQUxBaGZOVGht
      aUJ2cXVwa1Yzb1lzRW1BZi83b2xWTVEKLS0tIENOdER1Y0Z0c05LTUdLYU83VTRr
      UDI1dEY5MGRRR2g1cnpSUzUwM1Q4anMKw8Y55RGT+wH6x+afjkZggDOeml2jd8N7
      m6Fsaa2a1OzF+y2vwIpY/kgzrAEtvVXc2eceOZLAjUm+LMLfkAsxzA==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T22:31:18Z"
  mac: ENC[AES256_GCM,data:R2+4XkYKPv5Ao9d1vzjOHqhfUoDKxdNV7txtGsivxXk1sH6O1MEfljoj/xtri8X1Ri3DJ0piEjBOeKFzZBuG91v2+dErTdCzujBUWeOU/+tjfXIlCSOF9eUNu5OwTzJ8uDfblfsyfuXrWeurLL8SrFYgqH9mAy1cwuM9yERfXDE=,iv:msrd3pLseoWsvdyA8IK4SKa+1qcxXchAZdbowJlj2eI=,tag:PZxqT8x+nkaexGAPtzenoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
