---
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-secrets
type: Opaque
stringData:
  JWT_APP_SECRET: ENC[AES256_GCM,data:eUy4D86CSf6r2LXDtr6nrOpikl4SPyvKsXl7G7NkA0M=,iv:tdj6WpUW5LkGC6+6yN+FRaFT8BwzOed6q2/SzCoscUA=,tag:9X28wIUrmY77oP74t+vsVw==,type:str]
  TOKEN_AUTH_URL: ENC[AES256_GCM,data:ij7oJnV5PVtmMATQIKYkbr263PvWPHF8DhZ+i4sS5S6fEsH2AvjVVaS+FhPopNbq1bWP99vBHQkKjcGYYwdxatyZbgCgwZQbY6inO3+GbG+ybvRJ0tL6LnAVFd5aXN3or1ubOx025705JbUcC/RBzRlfrdcWNgbInh5yrTZJKtFN1/4L2wiBTMhl19t7o+FCY8R5C+I/4xG4YeM7mxGuFHM+9b1iUFE9rzSh0c0dEcxOaGNfDeQLJK5G+P/4Uw==,iv:wgrH+QEc6StNDt+Rt9EzJRy1Eq71mXmgZsBjlSgaSQ0=,tag:J/4jZ07N96QkwBTIBZ85KQ==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTit1SUxxRnEzNDV1Tzly
      dVJ5N1ZJR0xuWDZ2TVVxdjRobjF0MXdVZVNjCkIwbDNXS2JIS1hDYWRSSWJ2eUUv
      a0YxMEhyNEo3Qi9IUkdQelBidS8wZG8KLS0tIExTSENnVXFYSlZKb1ZDMXBiUVYy
      cEJHS2NrQVdHd1dsTHBXNjlENDJ3WHcKuzTzxTEO4/Ju6/6oRQ15MyEhUrJtXyoV
      jbbHvoUF63SCNaigA8Sk+lNBmCMtzuzJ9uCEfdqpfmCdSifrnt/S/Q==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Sk9USlhRYWNkbjNOMGdj
      WW92RW1PZ1pGelNCenZhZFJ6UmtmWVdPR0UwClZOSGpIUnNtaG1VcjE4L0dxN2dv
      WmxjaGhBbXJhMzFCdkZ0M2UwTnFGRmsKLS0tIHVNWVJzMlRnYU5DdEhFTTAwY1ZT
      YSsvdk03YWZYdm1seHd0TUx5UHpmTVEKQqCe2KQjl3BaQiLL/54ouIzD4oyeUoHt
      858B1SJA5VYqes2j8vVbLZnB4bmNnvkNvQqdaBLZ44BgLiKEPEf+Jg==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T22:39:08Z"
  mac: ENC[AES256_GCM,data:oncgdnt/NZT4AADFF15JzEpR+/l1F7RUnCfvVaVPOLcSc0lM/ek9/RzgNe380ruaxupIzdOg6X9632/PB8X9LeVBCJ7BvfpJ9pM0WTvqGypyfjtclm5gmAqY0GLY0aIN7kVcaj8VE1SG50C2IBQgg6jmEbzzlvHRoqHrlVGqQG0=,iv:+1VwvMSLmM2sLBcHQWi86ofc0Gsy7uva4R6LornakYg=,tag:KaiPBnsyHQvlmXWPHg5gtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
