---
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-keycloak-adapter
type: Opaque
stringData:
  jwt-app-secret: ENC[AES256_GCM,data:LFme5n3qadxeOMVWr1xyT/U6PnvsEwhxF0FP3ZeImNyJhDV0khEgNe2LZioSMVoSq04pDHi1ywh4tX57A6hsDTBcRIdRZdIslXkZ0whAW9PUrWR7t8V+5LV2vRWugS8WGK1BHaEe1xUCd7aiwA9CgHIVBB7sZuDh8bVsUqFg,iv:0XnkN2BdCMP/+NFqFrPNActvB+rlXoUmLRUylIBcVTA=,tag:Kv+DLijhO/FBRI3qNMKGhw==,type:str]
  oidc-client-id: ENC[AES256_GCM,data:Okv1ge0XmOke9zv/E72GjT5iaxKKbNr44RZFt9n8pPu9wQkkBHSM,iv:QYSlypqTYru0nmanqVWo5FX0RybP4eHzlHJPA6orAZw=,tag:+SYWtkJbLABjhyvD0xfUGQ==,type:str]
  oidc-client-secret: ENC[AES256_GCM,data:m8NoVpWPdNhfXriSAHJHV2A8n/wARNMCjXF5CAy28i4Rr2Lx6H0ctOP6gRv5zWsG6TeFIuzdMyIBF6Z/5t0vjbt2u7acAFFKYSFWj2+TU+DxcJA3a715otQ7keYigrI5j7mEgMaMBT3L/OePRNFmNdJJYrwFjyEV1aVFuLhV,iv:3L1jKPVwRU7oOgVrqTfvd/VN8izlfcjKtIV6ChVeSSg=,tag:v7xx1jliD3rpoWGGs7Oq6g==,type:str]
  JWT_APP_SECRET: ENC[AES256_GCM,data:OzwxtNWrjMcCyXTEmRItyZ6hfpKOW4zleTV+blO5kV48nu/NIZbBIwY8tunzfcaK4oJGT/oDdEURQKF5b9jdVhFjAz3yz3pTeLPML/wSZiRq538prvClP7Jz8mrUcelXVBR/K6kct00veBOLe5PN+itX/TYEmtDnxoYjW0AW,iv:0IjMK5Vp46WLz7sQZzG3c1eP4ekv5O5652u/KjMw6f0=,tag:gAhiMI83tQ6RPNXqo1Blew==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2hpSUhzVWlyeXV6eUo2
      aVd1QVVkSUU1V29jYWwxUVB1WU9KUHpQTlRjCmRUY3JCVVhPMi8yR0srVFFiLzJs
      VnlPRktrV3F1RnlmeDhVMXlUVWhXZHcKLS0tIEpxRTcvODh3Y1JuY1hPSGpDa0Zx
      eWxpTHY2RDVBd0U0VGtMQng1OFM1SzgKreJWGprYx182DQb8oYpvnwFdBCMSK7iD
      IsN6fOx7uqEBKdLhfT1O88sOIqzWIT6PLXJe+mlanYYMc/NwAKFLhw==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a2UxSzUrUGJLR3Z5bjEy
      dG5DMVZxL2pWK2d0UjRTeVBpTDBiUjBLU2o4CkVlcnRaU3pHaXBkTEMwZG1RdEZx
      SEhzbUoxRVE4UWJMN29xVEwzZ216SE0KLS0tIERvWlI1NHBnSzVRMFUrRHdSMWFM
      Yk52K3FlRnZpbHVxckVITng4S1QyRDQKVRjPqrF2edsMXjySyoFPh4oQuOfzbRm+
      Dodtta679esC7BkfzEBmDWuLhdfhAnqzKQZ4zHSJtwDQwTxKb0ZHNw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T21:25:58Z"
  mac: ENC[AES256_GCM,data:v3I+KKqja7tgGxmdMSnBvdTFl86qdgbo2eDqCy01LJK6LwST214tnzlkK2EzWbqMv21ouzjq8S/eMaAzIR/hhidcn/ApeXCa8F5HC/bZ8TmovtgFBL8ubeuRC51DzaDoVOSQ0KmfGxAYwe+1qBUvGShTpio2P1+DCO8WHiRd1xQ=,iv:rSrtEVDJctPr9h7JNnd/FTYH02LiKQ07NNKjT9JbFy0=,tag:ct9TiqXo+yS+8D/hauWifg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
