---
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-keycloak-adapter
type: Opaque
stringData:
  jwt-app-secret: ENC[AES256_GCM,data:ycXhznrn7fMySgrCQlJBGqV0Km1+ZyVplfz5TGbKWyRnWY1yMzDQ1Ld72XWykt1B3O1R9vNH+v9KnmoWb7+Usi/+AYB8WZE18dLPc5/2f/X/ewpUYvb0/E6LvHu3YU/nU/adN/u0OYD7XLa7yg8mSIGQPIOU/LSTSa+i4p21,iv:rB3o3oSbtM15dsVP0QwnrwTSH9iHAqYfbUsvqx7eCjc=,tag:xF87LPAVqVYOq2qyE/Xfew==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N1V3MFArYU11ZHV6RW1Q
      dUdWM1RMRkZrUm10MGQzby8yRUJ5M1BDM3h3CkV4ZWZnYkVMVk4yaUV1Mitmc0ZD
      UTB2b2JabXVXNCtMU05RaDdIbk92VGsKLS0tIFo3NzVpQ2pHS2lVWk82YzI4S0d5
      UnVJcmFKNkdhcTRoaTNyMFJpSTcwVDgKEcApv/WRwV58xrMdBv9NKE0vrZ4SWKaG
      /rhzRFrBIR8m3Dzs+/5/pRz5Q8ucdVQdHb7QvNQoaKgut25/2qWTyA==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISU1pY0xrV3FIUFNsekZi
      a2RZOVJZdFcvYURXZTYwM2hCWmtsMTdhV1M4ClM4cHh2V1N5Yi9JL3dQRlVDUW14
      bjY2K2N2M0NJcXhtaCsxeGZsQ3JhZWsKLS0tIDVaQnVNa000WUdDcUJ0SXc3SEdO
      Q3Y5NEVXR2hEdTV5RmdQUThtck5vR0UKKZ7/wcVwOxRzKQLKVIk9W1HjHmEXMmzG
      LtkZkq6vle1AbgufjZ+w2qtlLpX/GoRiMHXtN0NRNFXaDd99BW3mBA==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T20:34:44Z"
  mac: ENC[AES256_GCM,data:vYnuwvvupyP7U/8WI5VUoaevoM5btWSbiZOlHub88jcAWFg2M+aQkZ3dGbvzfcAKRZCROaI3/x1hGdPMh+Nd3D4OoI0x3LBvRWo/Y37VEdAbEJR9fm1JvLxjf2l8oZWjCCtenvoN0OEhWLohMLntNDXct/6cKV4geBsXgjXZJdE=,iv:GqM5/IWfzzugkX2bz6Bz/ereibcq/TNVCJoCWn8k1Pc=,tag:7OYEIMZpaLPmMBZnsJTIXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
