apiVersion: v1
kind: Secret
metadata:
    name: jitsi-keycloak-adapter
type: Opaque
stringData:
    jwt-app-secret: ENC[AES256_GCM,data:WIboIw3uns+0VTL2Ht2V22UBWwx+uNdlBziURmO6PHl28mGlJeJP8nLSKItTp3xjvUDr1D04TQJDpvY4Tye1rA==,iv:0Y2PUCoVEY+01j4WqFkbswW3wzg0hZtPCqER54a5bX0=,tag:OdcYJWv7er6wgQJBUkAlXw==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:36a/R2KKG2/AjqRJd30hvX53gGLzSaQnkM2HpDQ0E7rCYhKyOsPp,iv:42x6jTV/jMrJfzB5coRr4CTxnT1/atOIwCQZxQ5e228=,tag:uLLo6RkKYIh9pEootxZ8uw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:QGmz5pVqO7/ETXiLiKOT1zqlxeGdhdBXdvH/FJpg6IRG1/2okaYANQbzQVGqiji5wQexgM/KJmY8ULVCBqWoc6ynOyiyO62ZctXdBcoDUiMtrPxP+iJjSJb0PUr9miMbUkGdJuVPYXYqVRPk0hAVlmFC01y9kybEkEuSk3DF,iv:bmfmNvaqlGRT4vklP4k0F1unYTZXq38qrNPLKEw0Pok=,tag:tei2hq1tgFoEmDzGOuvynw==,type:str]
    JWT_APP_SECRET: ENC[AES256_GCM,data:CMhHu9UdrqzMcrmu8/KzylDCoUAxYJ3ZxAgvyjqZ/ViEjwjfu6fmGR1LPBv3riliYoxjXCmOC+lSMW0T3p5h5A==,iv:EvHyudlDQMRNyCumwvSZDmvh77xXImRzBCpGkeRexkw=,tag:qFFgEtzXpHuCglgcKrihDg==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydXliTTErQkNtRGRzWG1R
            SVVEdmN1d0JnWGh5YmlPby9qaTIwWHJSNTNrCk5XczNOWmVuanpsR3R2cGRxYjdl
            d0tTYUNUa2NoRE9KNjhhMnR0WEtzUk0KLS0tIDNqamUwemRuR2NPOWZ4QlkyZWFw
            cXAxT3RzY2IwUExNYVQxamgxcUVDVE0K59jEcubL3XN+gNpvDPCSFq2R3dRDgMWG
            2F/RuuQS1+LA+BYncg68zjZnlr7wQ759QSypngm9ExFfONyp8tvrVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYkJydUIrMkQzK0pYSWQ3
            M0hlQUVWak03K0JYUkVjTDRaSWc4Y1ZIVkdzCmxWZnpSYTlidjYwYk9uOCs1em51
            Y2Z0MDlYenNVaVJwblE3bGxGSWJHQ0UKLS0tIFhjUWtpTTRheTRteEt2cDdrZXQx
            Um43V2V6em5ZLytOUDdpeThRZmJFNE0KxPb+zO+DyrrGwRHlrsVLRTdcQ/CteqAV
            ZY+Z40Z/I4Djh9BrvaSZHszan+y+iUbk8r/zR26qNseLUniMQWnYjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T18:16:57Z"
    mac: ENC[AES256_GCM,data:IgWZ3mkPNzRg1xQBQlTSirSyDDt38x6QV1lumsb4oU0zLTbuVJeTiXxAasR+quDCSp2886JNy8s8xmcuwNMi/kJPlQ00RnthAzXfAxDalJpNGao3GrPEeXSAly2sFo95q3DL4vw9NmEtEqvNSa2Suyawa0wiWQCqcIzTpwy1Za8=,iv:oGQyg0BRt9SnHPGIH/gGJVeYShMNDCK9eLMtEdts674=,tag:9pUzboqw9XGKe7y1zxoEKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
