---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jitsi
resources:
- helm-release.yaml
- httproute.yaml
- namespace.yaml
- keycloak-adapter.yaml
- keycloak-adapter-secret.yaml
components:
- ../../../components/helm-configmap-reference
configMapGenerator:
- name: values
  files:
  - values.yaml=values.yaml
