---
publicURL: https://talk.jfp.one
tz: Europe/Berlin
websockets:
  xmpp:
    enabled: true
enableAuth: true
enableGuests: true
extraCommonEnvs:
  AUTH_TYPE: jwt
  JWT_APP_ID: jitsi
  JWT_ACCEPTED_ISSUERS: jitsi
  JWT_ACCEPTED_AUDIENCES: jitsi
  TOKEN_AUTH_URL: "https://talk.jfp.one/jitsi-openid/authenticate?state={state}&room={room}"
prosody:
  extraEnvs:
  - name: JWT_APP_SECRET
    valueFrom:
      secretKeyRef:
        name: jitsi-keycloak-adapter
        key: JWT_APP_SECRET
web:
  ingress:
    enabled: false
  extraVolumes:
  - name: custom-nginx
    configMap:
      name: jitsi-custom-nginx
  extraVolumeMounts:
  - name: custom-nginx
    mountPath: /config/nginx/custom-meet.conf
    subPath: custom-meet.conf
jvb:
  service:
    type: ClusterIP
excalidraw:
  enabled: true
