---
publicURL: https://talk.jfp.one
tz: Europe/Berlin
websockets:
  xmpp:
    enabled: true
enableAuth: true
enableGuests: false
# extraCommonEnvs:
#   AUTH_TYPE: jwt
#   JWT_APP_ID: jitsi
#   JWT_ACCEPTED_ISSUERS: jitsi
#   JWT_ACCEPTED_AUDIENCES: jitsi
#   TOKEN_AUTH_URL: "https://talk.jfp.one/oidc/auth?state={state}"
prosody:
  jwt:
    existingSecretName: jitsi-keycloak-adapter
web:
  ingress:
    enabled: false
jvb:
  service:
    type: ClusterIP
excalidraw:
  enabled: true
