---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:oXHScIet8D6jaYcNVzbBxtBgVRLtcErJh00hWGFl9Xc1MjrdXOGCEw==,iv:q/nUSTmwY3lsANtZNnYd3wSo9nGHAvVb1mv5qrtAp9o=,tag:a3KLvuc66jyZQpsyu8zEqQ==,type:str]
  client-secret: ENC[AES256_GCM,data:JaK0ZyqJ3U/f4MPmK6nwGGxnSrFl8u91dRYdRYQ2bUUFV+AU86TMhyW909yRBg/CYddSiUbrKNqpOHIfJ6XV18OqmUWkwIDyk0wd3CweAplUtCBBieAlsWajv/9y78LBEzm5scGD3E/tyqq9yhzLVIRlAZSCJKHMwkwXdTfFAxE=,iv:1+0rHRB4oY+1qo5py6LFfQXuGiPdik4Wunn3ECoPhHg=,tag:6ILK3nR0YhQ5CrlThlm55g==,type:str]
  cookie-secret: ENC[AES256_GCM,data:DIiPvFFkzj8FuSPWPqiwSX3uqY9tom71FNJQic2UUOY=,iv:5O5wzEwxFAOVuEOoAebyN+GKLyTPlX2hDgfv1IRxZRE=,tag:/bDJ3qtg8pf89o7LXfW/1g==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb3JJdjE4SXdCcVpjZWNY
      RXRKTnBkUnFtMTJxVXNIcDBBQ3FMSHFUa1FnCmIxc1Y1U1ZCdGsxemFEY0FROG5n
      eVB2ZW9TWUlleFZIeGZUQnFvNFdKblkKLS0tIDViOXhNSll0Ly8zQWlPN1hyVmxU
      NUJHQWQyU2FBVlBsZlhqUHhRUUpVZVEKTWcNqdfSLSOocvfL2yE34gP+8MtZTtQS
      NQZ6oJbKAL+LcR6eI7C35HG+t+QNnORiPjJ+169nSmx2t/xs3g+2ZQ==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdWp5bnF5TUt1ZW5aeHFi
      RmNwK0x3bFJ3RlFMcytiYXN1aWluMVNpY0hvCjF2UlBqOHM3cEdFMStJeTF6Smlh
      NUIrbUgycUpHV2lvM0JJMUU0T21OQncKLS0tIGlRNFIwdVlNaGFpWW91VUdHUDZl
      QmFWdElkSUZmR0pSaWxpNmFHUVhUR3MKCSgmREkx7UPh/1iA3vc+3A8/7Vgj6szF
      7N/eL8exgmmLcPjYhLOImEYj2/SMrKM8s3s1XJq03aQPVzzv9yfyCQ==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T07:05:39Z"
  mac: ENC[AES256_GCM,data:9bnBLGa/ctFdMZ6OPnDeifty4IXmHF17jN/RQihwMhFlx175frofrQXi0OK4wHDtYvzGZ1/wyIjvIpNrQYaiE2Y4o/SCyGu9F8pUeE6SUVupeMZnATPdMWN81cei6yHVIbewmeHTR97PpxXmq+rjFa/y2LN+4RBBMleSguDmPdA=,iv:6oE32J8ptoqRJjIhpWJTYMGwfs3PqxRGk1Wfw4GO55c=,tag:zvcacCnsywDJBPGxdCEkXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
