---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:Hnzh2Bqi5Uuj7s+kdja5YM37720faK/k/354xQHflYl4eUzMDbsnZA==,iv:RgiNBR4efaXZikYwyMtB4047Fhf0muFg+8C6cF342lU=,tag:XTf0pSSp+UcGjt+b0Hpl4g==,type:str]
  client-secret: ENC[AES256_GCM,data:ymkR8z/CoYDYpi7VOEz23ppUz2HEFegoTgRQjYRHiQhgm5xqnpNNqM19WI65cIsZoQ73u4MkiD8fJyV5wDHPQfHIKM45u/ENMjBC4yeSoEMmqqX7tZnmM3KFurhZ7vHULTkqz7FB+z/lE2pcg6GNbiLp/Rm22tZ2XToNUBJiWys=,iv:q0Exu6LSJAbKWO9Iot9FDi1cXZIivpXiNBYHa81vEEc=,tag:bG1zTCnx1e10uU8LNByQ4g==,type:str]
  cookie-secret: ENC[AES256_GCM,data:SDhpzHMxwCQLmTmeRYWteKx3jr0pICXSXLX9v355SWc=,iv:Ftrg/6w2UrbLm778JGG26F8zDLlvJl49fZMuY2SEhVo=,tag:VPUPy1xlDGYtp6tDi4yloQ==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRlVHVkdOSXowRVRUN3hO
      QUlMUTY1L1Z3Q01iMjZVZDVLMUltRXBxSlU0CkUrZUxaTjZqdkU4bjdRcGI1Wmtp
      V1JkNDdOQ21UdXFvcTFrYURYRjgvVHcKLS0tIFNrVzZXYzdDRmxqTzR3NllwQnli
      YkFQTGlXdTFmZTFKZ2FyZlVFZTc2SXcKiuMJrfF7fxGE1WwsyvgsBK5L4I2v4oFx
      11abzFYP2wVfRJg4LQiYmasGJamzr4Vb6kLtP/GPg18vaaWgblzwuw==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Qko0VkNEZkhBZDdyeEt0
      ZlJJa3hoKy9CYVVwUzg2ak01U3FOenErYWdzCkkwQllGWjdWK0FiUFNGR0xoaXR1
      R3ZrSlFHZ3laa1NuU05IYk0ycjNHaTgKLS0tIDRRVXUwakVhcVVPd0lDK2VGZkpM
      RndjZGcyZmRhWTNzdGw4aTBuTzExY2cKT/ujESalh5TNur/1Y4ouLcZ//jcJ00D2
      GJivHDs3PVThCpHqzFNZMRM/JvNG6ZAPgB0nyEtlagnZkTCTDhxcQA==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T06:54:25Z"
  mac: ENC[AES256_GCM,data:zHIh1L6AJPZZmNIRNOmbWCqc5bpmGcqxycxWhCpzUDLPqP2nTp/GUei5bLC33PLbXzhey+PEhP8hWuZ1ZS6qfogIZKerkRu1O0xxi0oz7rm5IPL4zegmFWqSGUQHPPO5/OSBcOe4wK9dOR4Oc7el7A/UQlTX3p/QXKb5qAnAJ0I=,iv:RBKVzCZq70acPZlpgqo7ZpRj7BsQi/tJIRxdFC+/i48=,tag:eK+SvtHg6mCx9DS6kO7iQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
