apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:vXxr9dz1ghYgva2LPvyF4ncy8D8UTJcShePxN/JdSnx4GHQ+XKaeAw==,iv:igdJZ2UygiOb38KqXPnirTqlzAqjjfy9bC9+E+qJn34=,tag:NeePZxNJm1KdL/KNutBWdg==,type:str]
    client-secret: ENC[AES256_GCM,data:r9or6pg/caMBjcrM/Hu27MnlspslF9CrijjepZC6MutT0qzDpI/IoTOc+FglvZg0flIQShXq5oRse8mDpuBy0Xx/VvhoSF2hUbiai22tyusb0x5ev0T5Fp2MuBubs+/wQuURYq8uvd3lunsFcd1jMqNAMPDdLc2sAY2oX+Sr33I=,iv:pStqKlo7MvyT82blYNXLp4zWtY5sYCZcn+qpBbljJxM=,tag:E5FrjHSrweqVQyK2UL3JiA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:fjmiTiMNOV+1nKSsMsbwfLqMBOVybh5+/xUSJkoEHk4=,iv:hufMcWLTDSGkkUB4eNZLiHJcIaBrE30mxePgygghIUY=,tag:fpQIxJIrYOdH61SN999R6A==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrODc5NmZIeDRlN0RYZ0F2
            WEZwejhNSC9Qck9QSkxNdlNiRnhjd3pSQWdzCjlXaElSaC9wVU5XVlZvK1Jmc0J4
            V3g0NkcvNVBwL0NaZnB4U09VZmxkQVkKLS0tIEp0dU1hU1RmUXo3elJvTm5lYldU
            ZUVtTnJnVzlGbjdjbEYreFBvT21pVEUKs+Xr2fZ2dJKUk767ySe+gN+35/RJG56Z
            j4YRScgfrDADHDJh/tDwmyJtsae1IX2PthYhT8NpJxobkNpjKby57Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2alZrcCtDSHlrS1hnb3A4
            dWNRVG1tSGcrUk14M3hYSkFYTXNWcjJoYUZBCncwbXZRNnBOWHdZNEhvNG5YOHJC
            WXZZSGJlR3d0dk5Kd0ltWGlKcVV5S3cKLS0tIElEb0VLYzNDajNuOWorNy8rK1lv
            bTVSeklYTy90TU4zZUtTc1VOeTRPSHMKzYmuBcYbIMY6A5CoIl38mBUaXKFJomEy
            DGzaUxgh2pI9OyvxZ/677IEsjcp1GuMkKGQc/Xjh/AdP98/Yw4frQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T18:18:09Z"
    mac: ENC[AES256_GCM,data:XhlVNlBKw+pzITSdWtuhU5aKxdhxp6rVRsr5trduLPxq9So4hvSzu0IX+UdTK2qCACLcnaA4z0aMUeQvBhqeY/9f487IR2yJA6cTB/ohWXnIAsvYL6yecxIW9fMir+C7igKA3fW8mbfi1hNpE97HvXiq+BcjUeUmoVhs4X6FXoQ=,iv:uvb2n+bfWPPPAcOgmEUt9eBqRv5pnp5Gry4aX1aXIeI=,tag:XPKsX3aUMY55/OHrRdYdEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
