---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  values:
    config:
      configFile: |-
        provider = "oidc"
        oidc_issuer_url = "https://sso.jfp.one/application/o/whoami/"
        insecure_oidc_allow_unverified_email = true
        email_domains = ["*"]
        cookie_secure = true
        cookie_samesite = "lax"
        cookie_domains = ["jfp.one", ".jfp.one"]
        whitelist_domains = [".jfp.one"]
        skip_provider_button = true
        code_challenge_method = "S256"
        reverse_proxy = true
        upstreams = ["http://whoami:80"]
