keys:
  - &host_jens-pc age1y590v04t77p2etxycktq8xm2gv9qghrywe7r0vj62uu8kaec7gsqwq3ewj
  - &host_nixos   age1687qcdgp7uqwy9k43pn4lht5rr33hl69yakrncaaa46hd9t7e3es0qrjyx
  - &user_jfp     age1p3cvh7cnc8cn05awxytlxfqvm2kchgyq85mc78nxte3dhgg5m38syasdfj

creation_rules:
  - path_regex: systems/shared/secrets/[^/]+\.(y[a]*ml|json|env|ini)$
    key_groups:
    - age:
      - *host_jens-pc
      - *host_nixos
    
  - path_regex: systems/x86_64-linux/jens-pc/secrets/[^/]+\.(y[a]*ml|json|env|ini)$
    key_groups:
    - age:
      - *host_jens-pc

  - path_regex: systems/x86_64-linux/nixos/secrets/[^/]+\.(y[a]*ml|json|env|ini)$
    key_groups:
    - age:
      - *host_nixos

  - path_regex: homes/[^/]+/jfp@[^/]+/secrets/[^/]+\.(y[a]*ml|json|env|ini)$
    key_groups:
    - age:
      - *user_jfp
