---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-jensereal-pull
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:I1az0Clyz8eUiTnHFNhL2cJt1/7L58DfY9xUy5+X7dnbBoAaar/mFjCoBmkKrlfugAjww3L1y4A+LUnnyl+SOKgNsYuUCHzLL7otKvIQQ8yxJWoU1e3ZH4gxhBcGotziZnLH9q3tgbjqWWZkKG1bb92/yKHuDzIWtcWf9413n8iWkoOagU05,iv:fw5QGS1W28Bs35NeWrghMTFCOu58iUi4lr26/OyF8xk=,tag:/kGVM3PkAPfTigLiDwIOVA==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRWZ0K1hxQzUvRHJNOWRZ
      NVpRbk9MMWp1VldiSDJsQ3k5eEwvV09DYldrCnI3L3pIdEU0MVQweDZiYytEdUhv
      OUttUGZkYUhSVlhVWnhOeG54WkZ1NEUKLS0tIHdkQm9RUi9lUlJabnpDRktXNlhp
      WExDejF5YXBNcGd4SCtBb3lvTkVOTGMK36soAS61IAd5zNbKk7a9x5/SQVwYjCLs
      ZIm30O+nqfxPpJJr4A8UGaCp65STbbyfRXOy5IrPW9dRnwE+eEZEww==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T20xTFhEVGVCdVVtY05x
      M2kwbWh5aS9Ndjc5NEh4REF0VHo4UVg5SjJvCjMyMytiSldnemlmU3NQRE5VK293
      Z0xDQUpFQytwQk9lR0I0cm9DZWwzcmsKLS0tIDd4YnZKVXFwMHhpNm5yOER3UDVp
      cGhDaWtSRlBYUGJFcmpIOXhJT2tDZWsKiFfyc2fKaG7b0xnTpuhpDTcB0HWjc4tn
      9Ev1OpNmAjaFxBluiAuW27DOtVpqRixqNnbbmdDpLHeYiooE1FumTA==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T10:07:37Z"
  mac: ENC[AES256_GCM,data:ZOXBF1fKD1daGO/inyNiF4zygX9Cna6PEfn91Jy0xhU0NijhyxfrJ5fT+CP58rUceqK6n+ojPrW9sSJHD+MrX3GQFWxXmr8XUCnVTL4oioeS6CeZrXHpdW/MWJVN7HkfIFSLDpBu5t2MJlUQgVB6Q8PnrMzm/g9cMiYPdf7yggw=,iv:EpP1sw9Kdr2viAF/GJhSBUASLM0igerr1T1VRAGzkKw=,tag:g7cKoTAWK735LxPfMJWgfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
