---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-jensereal
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:kAd2ypD+YtCSMtI4em2QRwnB7/YEmgvFxrglSOOR2qW4Hau8APDWmX+zH79dBH5VL0KFBc06TQlPGDigo6iE/7x4ofySLllxHvC5GB9x2qeqcx2GDHzYYInCHwoaD4KcUkFdYttHp7vpLhtyJUDaFIBUCqj0Hv3oQxrVFzR4aXBKHr4N5N5m,iv:/T1HoVAthtAwQarOsjE6S4m/qzxt9HRz63fItH4Gegk=,tag:YzQ6/DdGf+MWgUsH7NzR+g==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b0p1eVRtMFc2SkJ2d0F2
      NjVqbTVkTHFGM3cxazhFQWVka2tITUxSOGxZClZhOHpxZGx4WisxYklWY2l6WWl3
      VTFKQ0hWck94TEZ1YVFFcDZhNFNZSzgKLS0tIG9ZN1c5VXdGeE5TMk5YOGQ2RTM4
      eElTbDhwcStpaTN4UTZDWXBPT3krVHcKswmBnYDzQKl/pnjjNrM4RdsTHNvb0Gpb
      kPlNrzMeoWDAObxybR5pP6UCZoR9JmF5qo/TTcUKG6F+CGYXxfIaBw==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdVROdjNxdjhMb3lYamdQ
      Ym9kZTZ5VmhJT1FhWUxVRGlrQk9KckR4eVVjCnpidDVrUWRwVmNzMnRQVVV1U1Fz
      a3VYcTFRZVRvbzJ5R2RpbjYrUU12VGMKLS0tIGYxUHFjRTVaaGtJMEVkV0R4bDBZ
      Y1FtYUtkRVF5ZUloR1FXQnNNc2FCZ1kKOITUTJn0ZeA8z9+VKB4DYd/xoxJrfDUs
      cgM2Z+TcwBDfKibPrmOkxAGkS/+akSBIjwTv4OxDkvVfCSftvwvh1A==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T07:40:40Z"
  mac: ENC[AES256_GCM,data:y2sqr/X1ZanlcEGJKXUg0JplHH1t1TVccd1/WMjMnLEfb/39CmyMkJAtJvMHJ6bmILc7Ax/F1v//ZpwyOhWUhxkjRLPW6Pze/7Ae3xcykio2VvyrGiCKy/gca7+lvMmYI/Dt5Xg8xSO/p6pKWPPPZ1Pic2V3aa7mD6Qdo3CPi8g=,iv:rg8FXYMVLBlSQU/lX9jnNpbwCU61MDjmqv1hWagOo2A=,tag:PNNbp1g9T84j0rL0oyRMQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
