apiVersion: v1
kind: Secret
metadata:
    name: ghcr-jensereal
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:0sktRtQssLk2wd1cVTuaHlFIJNJzihKTijKoi9+Kq/bP9lIyJZGLlg9I7kN7tfTEYT4UJlIjUlDme9pbQX03Z8sNLNIAC5IRglF0Ip/vev3FWJvG/EIuxnrEZ/R8YT3fdnBHGhsSH9aR/IvC/cW9gJ/Cp9D03OwqtG8UJcAql5nBs4LEhRgg,iv:wfPpX5F1rdTJvy1Wzmr+Z+be++DmZq9vxa3HpKzmWZE=,tag:n9vx+1L2+yGTux8BGNDi7w==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTC9zRHNyaURsYU0xOXpI
            NVkwRVQzWUZxaHZlL2pxWUZFMWNrWHVBWTBBCkkyNFZ4WFErbnJhVDFlcHROaHE0
            YVhxaGJqVFhFNStjdzFwZ1FEMXNKQVkKLS0tICtUZHhYM3hlaElLalVpTVlTNEVS
            aUQ0OFRrOW5RK2w3Nk53My9SNEdJSFUKvG9UmXVXWacjWSY/xW5H/HwsSDsGEh+a
            /CM4rjrPq66BttIkNm51xi3kbhXP5JIswxXcmdwIc9VtuKSzqx+vKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUHZsUC9hZlZrMjNzbnl3
            bE9oT2JuR1dycGlKbU84UmVRdGQ3UlQ2UVVBCmEvMUp1UU4yeE0zc2ZhaE1nQ0tZ
            VytJWW5oSjFkZjhUaDhrUjZFQlAzSG8KLS0tIDFVUWsyN1NRUFJHOXpCUHVibHZy
            VXZPdWNwZ0hFblo1MmM5QUZQeForMkUKvbFqXDUXtWsi0F0LG5AkcOPHhcl7x6OA
            S5HujtpSc4ntYQMcscXYpLxvR3TgtR4IVsOhe0Op/gOEA+lLETtN2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T10:07:19Z"
    mac: ENC[AES256_GCM,data:jg6RkcbXgEcze8wbEevv1MsYrtu4O0w/2Fl04/bi1MPoDbStng+ipMc/wqQu1JpZImuIXPC9zhUATn0MXJoyDEvzu9rQFvlR4yeC6UT4aUzGBppd9/Y2ju9t1hg5GWQpUpPv2965V1Ubm0LGGcVMDPCHCAN2ys0qwDH7l61RL1w=,iv:MtLiTFb214d5z/09XgjAsbdUt93d9eIfHabnS3jbi7E=,tag:7D3CvVIkqKxk++97OvMjWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
