---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: whoami-authentik-blueprint
  options:
    disableNameSuffixHash: true
    labels:
      blueprints.goauthentik.io/instantiate: "true"
  files:
  - whoami.yaml
