repositories:
  - name: cilium
    url: https://helm.cilium.io
  - name: fluxcd-community
    url: https://fluxcd-community.github.io/helm-charts

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.19.1
    values:
      - /run/cilium-values.yaml

  - name: flux2
    namespace: flux-system
    chart: fluxcd-community/flux2
    version: 2.17.2
    createNamespace: true
