repositories:
  - name: cilium
    url: https://helm.cilium.io
  - name: fluxcd-community
    url: https://fluxcd-community.github.io/helm-charts

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.19.1
    values:
      - /run/cilium-values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - --server-side
          - -f
          # renovate: datasource=github-releases depName=kubernetes-sigs/gateway-api
          - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
      - events: ["presync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - --server-side
          - -f
          # renovate: datasource=github-releases depName=cert-manager/cert-manager
          - https://github.com/cert-manager/cert-manager/releases/download/v1.19.3/cert-manager.crds.yaml

  - name: flux2
    namespace: flux-system
    chart: fluxcd-community/flux2
    version: 2.17.2
    createNamespace: true
