---
apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secret
stringData:
  github_token: ENC[AES256_GCM,data:+WQnv3TV2TpNZ0FSU09iO0/TwOAjinEwcqlrJrwaKDQJbLbkbI7dcw==,iv:04hGE4pCqc9jtYKZ0yJTx+TXF+Zc9SbVbGYl5/+aIaU=,tag:4Hm9Psw839GHkWathDocuw==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZTdTNjlPNVZVdlk3NFVr
      ZFFFUWEzUHFzdTZRZFBpZnhjZTZWOTFaT1NNCmU5aDVvYmRhNDhSR1cyS09raFZB
      eWhMNUxjeGhMUzRSZ0l4Vy9xZFZod2MKLS0tIGZ5STBvQVdyenRMMlRXZ3RURUMr
      eVpXNlFvdE10Y2h0UmJEbS9waFR4OEEK2Hs2dwvfT8Wi5Uo5Kx4WNF91B+byujV3
      Tx7E0LQCUxypDLVT0lzq+liahbFR4drim6AMiBMoPYpSbwDBsL2dsw==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraWJCT3NMMEhQMUtQai9G
      L3N2MzRBRWhyd2VUYjhwZlBRR2lXZUlORGdrCklqMDBQR3dtUEdFTXlWS0ttaG9a
      UWRPQXRKa3Rub2VhQkdSbVNVbmxBNnMKLS0tIGxxQWRHaldxcjV5Wi83aUlwNzRx
      d01yUWIzckk4K256c1ZBWTVEVGRHMFEK4lan9NTBbDXj4bhKucGwoK8Rt4cNpeCa
      /Ati8ABHDgSzSXUBsO8D2VcPwc8OEvTsu2OAjcQOzNC8C2i29YRm6w==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T08:36:13Z"
  mac: ENC[AES256_GCM,data:9He35ftMslT2kOFID2oGLGJ/nBB0jqsBdmdv/WHUw36OxDlOmEizYHM2InoDfmFljBkExtNplTigmVUrhajTzDmAMwAYuItGcw8l+BRcQkEZFgE8JNjEeWFNBv5NIqpGkgoSXvR9bvjP6ucPHjEycIshZw/5bd08netrmrOFcPY=,iv:Tai75tU13ma+U9PLAjFF0Qtn6V+0+3H8dQawbKEbHaU=,tag:KapRdbJKzZDBh1EJzfojVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
