---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:qluBQp++5JFUGekise858GJ5osTjVLOk4sO3HKhqjBd3KyAFZNMPTDDxPjglrOOoDUiZ4yNokH/H2vQsRL8DnnFrdBg95Hpls3M3xbXdick=,iv:x0F6W6SFMaR4wU2xzLZd6wOchRg5Sxzo47Cy8d4lEUo=,tag:55UnX+uDp/71wgfo5Oa7Gg==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:ZoVKQXDJhQBy+5irC2va7zwHnhrXnw2Cebzsm+8J,iv:ELqRHiefwM5jg5k10psWPEmtNfbg0D2r7FGRJ8fDpW4=,tag:KuE0Z7XBlZG2OfLNAxK1UQ==,type:str]
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:hjJAtGypy7fSpspoQwb5N2h8ZA==,iv:gZbVtkR+MmqeB4q0AN2zaDUjixPQYnn0xcZjg+b61WA=,tag:+biDbti2vFHFd/wWOn+ATA==,type:str]
  WHOAMI_CLIENT_ID: ENC[AES256_GCM,data:jXhrNiLO5oU9fbQkbLfoVg3PagWfubluppuf8gxHx5gfNNYhehGd/A==,iv:KOJ08SYxrtPjaWTsDHKQftgWaCQHwm6jW8Fs87P50zQ=,tag:GYX6UnU3Ju9pZRE5eLKy6g==,type:str]
  WHOAMI_CLIENT_SECRET: ENC[AES256_GCM,data:y8w0bQRMqG1amfTslyFl728B6itov4lUF3ghazoGjYOJyap5OFW+PPcJ8jmGZZEPBwlXPhHren+xtdZ97RnSSMXpmoQwCKrhVmNnMQpiB8J+cQy+t1bHPQ9Cj+gxIW2btIiRFiOoX+qQEPF5WoxW8C6/A2ST4mHYJg8DBlfqjGE=,iv:Z5lji7nCOBXY8cS9IjEVVDlKsMwSJTb3U4Msbz+HXlM=,tag:5MAxrhWyEztF+2JaBRXyHw==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q2Q1SWVGTVhPM2JyK2li
      TlBRS3NrS3NoSzF0ZE52WGVGdCtOZGNDd2w4CkJDenZsYXlJeFJjSlRHYVNjVmpV
      K1V0M3JNWHZ4TVYyN1Qvc29iaVR2WGcKLS0tIFlQU0JWa0x1UHV5SUF6UlNlRDBZ
      RmtyQ1Z0Q3B4TjJFOW9RNE5uZno2Q0UKkl8TEH4qR7KeaeuXtxSKE8dVGJB8AfQS
      F9w6ZrExzbuwvb9HID6IbTWxkF24JsDXkA2Vl1iTMtnc3w89pYn4Gg==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa3N1OUdDV0FLaEpSU2FJ
      NDdnV3hIVmY3OWFZRzFDSC9GbmdlNG9INHpVCi8yWUovSE8yTGVxYTRudkorT1RQ
      bVBFZ3hRMjlkb1lvc1FiQ1l1bytGaHMKLS0tIE91V1ozck05MUlnZEFHRE5aK3FW
      d3I0MUxDSC8zTUhIZEx3ZmtQWDNFMmMKXjFsaH+ljlOrYYEVIx54ASZxriqTcOUB
      vIdAn/25Thxx7MU3KssQySDm/XC+JlKhQy9ph+MwDueDdav4mO475A==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T20:59:42Z"
  mac: ENC[AES256_GCM,data:nZHG0xroJYzgd7MxalqYyG/gehRgR8Tt9s1QqsPtMLW+SWy2VQtJUF0FdTpf2pW4Mqep0S1896Un80S7t27DkuO5f5bVihFnvsp0w11nhYSLb0NiXJKJq7frI+ChW7T8jFO13WsQom/yQrr8vKwrjwu4yzcIVY9XP9qg2BbOAvw=,iv:WWFuK6UaduoMW8dwWa901rADGx0OPrtj3jLpmKah6D4=,tag:zZD6xhk84FQEMlpWbx0eHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
