apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:xHwwCx9Wg8rEYQo8y9BM940Si148+gdC1JlwcHcgaD7e60HfKw4kwl69cyrT5uqU0+717eSiVuDaAMlm5c/lDvZiK7OAQoV2VL3+r2++6SQ=,iv:ukwfDqxeNvEh55o4MWji6Ur62T3C5qkrzxvapdRat3Y=,tag:Gqg2uTUKxUiHCeuEzCl/qQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:PKkAIPwpRzTB5P4k5PYtngxgoHBK5BUxcZdavQhy,iv:QzXeIAaR8iMhhip5u6UHDOXrfzo87vRoRP5cTcmiUEU=,tag:8JrILNyoh2vaomNJHQbahg==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:V9bQS8ppk940vQaUSqa/mRN8uQ==,iv:Ep1xewfiAJ+kMHcLObjQmSs4Zb5j+Zai0cXl7ZJ2R+M=,tag:/rNu6cL4B4g3sCNvmCIAOQ==,type:str]
    WHOAMI_CLIENT_ID: ENC[AES256_GCM,data:EhlwpwVf7yhBOWcWtZtgKpee+jggE7HGf4itQ9RIbF9lJma/lwe0vA==,iv:RLDqxyePYSXOdLsafnirDVNn5g455L7BOVoAYzccgr4=,tag:bageBdqEAbjGLCLZ9fJn4w==,type:str]
    WHOAMI_CLIENT_SECRET: ENC[AES256_GCM,data:uxlhN/YsLnrsr/kNJmMg+j9HT6e6pKp8HvNQrbVvv/1VmrSWIWQhiy5T4RY3YDpUKy04QdkMEulOpSH0FcV1WALTxDtfpV+M/SktxVpydMGCTPcoTzjkVn5O8VYao/ejgCFQoXeLBZY3/ULXGK+FNdJrMs20NtDMq8S8D/YpnFY=,iv:Ca27RNlAg6S+aIzApRk6NhrEyabn+E9oz2EERBMsHRo=,tag:JGYBEwHBTqtPaKcWv2JX7g==,type:str]
    JITSI_CLIENT_ID: ENC[AES256_GCM,data:JB4+R3yWHKLjSGO7nCh85SxK3dHwemFGIcxhqljc0Rvp9mQyi2g2,iv:gI1/SpUzgjdivy0f/Uj3Nako8VvKK8ASJBRYKYfltB4=,tag:pBNhjGIqMLYUfX4dVvofjw==,type:str]
    JITSI_CLIENT_SECRET: ENC[AES256_GCM,data:XynIzpDfBceVINW5KFtxA3u9xPz9cpDdiDr6FsbcnvdPMCKBozeQv6m1jPDsk78tG+IX8EG+FLot2N5FlyvHTfM94pbV87K0Q92dPwL9uL3aCIFkUO2FTwITplvzAd9AJlIWAqOT5JOQm+Fwr446jw4IS6wUuJ0qhoUY2PAf,iv:jpcI+tWn93TBNnr3E3FYCdumBrtug/FHSaXiMj9RUg8=,tag:VaQX550ZKzpTzEZ3pa3v3g==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSllVVW1jdzlEZ2F5am9W
            NGpLc2dzeUR4aExDTDd0enQzRUNjVThwS21vCjJZSEFoak10SEVCRzhONDJ5VHg4
            bjExSlU1SnhkOUtERE1uVzB2eEh1SmMKLS0tIEJheHJRTlVaZ3dvTXU4SlRra2pD
            WE0vSlZ0VGc4c1NKVnltMW1iQUcrSEkKKvigknyUZK/wOIXReBgQce1dV/+Pn/wx
            q6z+ft6PMe9AmhK486oYIIrWz4hs7uc6y151tyXkbR/EABd2PsCZ6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbnpJeFNwRStSKzN4QWM0
            NUVXRDdFU0lFbHRORkVxZkpzOWxmMDRLVVg0ClplcmQ4a3EzSHhLNDJuekNrWmhS
            a2lISGdxOVJaTDYwczErZkVKQjY3RVkKLS0tIEpMN3ZCNXExQUFLSnVMSHM1Vm05
            YjZoS2FkWUJnMFhDc00wMUlVVHVyRkkKBZwThVYQdEDbDZ/e/qxTEJYz1MYqC282
            ugzpKuAaYiNLnnIP+lc0LhpfBUjpDmIvxhvsR4MZ/DMrThQe6G90yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T18:17:38Z"
    mac: ENC[AES256_GCM,data:YX+ypPsTShXwk2hSV9zBADlevmlkmUQWSamF8sLf1WOM1+3JfQd85sqfl+mj97PVwM4g557bERuwYRtmWZHrkDB3MWYVK9lKKbh9PG0JHyz3LPR81Epj4WIH4B/OUoaKjiBSAtU7cPYdP8e4XdXa/d3jZpc3z3Jy8HqGhssSM40=,iv:7XY5suqqpxjFe+O6wkdeGDIno3ZW/Hn/EKmt+7wWzS4=,tag:msLX2nLxmyt+ZlrDQFGmcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
