apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:FXfRxZuU1ru8QXEV6eu02C81JxO34kNp7Sx4mOSZjte0xkyBz7XYuM7tBvx+EoG4fEdQGtHQ2qlLAXuUTQF2Dr56MhhfCMFUOT3hKvQre/A=,iv:ukwfDqxeNvEh55o4MWji6Ur62T3C5qkrzxvapdRat3Y=,tag:UktaraMQyoYWrsa3aGiPwQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:s9C1ljRAQspsyEknG2xLhUOzHyYKEfCOYrsSsUX5,iv:QzXeIAaR8iMhhip5u6UHDOXrfzo87vRoRP5cTcmiUEU=,tag:EJHnmJc7fN83Y6iTObUpbw==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:lAPHW0bbkdpxxP35IbZNWLE4yQ==,iv:Ep1xewfiAJ+kMHcLObjQmSs4Zb5j+Zai0cXl7ZJ2R+M=,tag:Shn8VQhO1zIuYoxDpmfYYQ==,type:str]
    WHOAMI_CLIENT_ID: ENC[AES256_GCM,data:q6yXz29KpGBnfZgYwkuG8YR/7TUYhycp06hR8jYckd9bqTDGmySvYg==,iv:RLDqxyePYSXOdLsafnirDVNn5g455L7BOVoAYzccgr4=,tag:FX5i8VNH1FHYDSkuKENOMw==,type:str]
    WHOAMI_CLIENT_SECRET: ENC[AES256_GCM,data:wf+VpJ0WZKQuI/RUGmjXvmlEIQmSynYE04n9G8WSIdaQmQRjaViYdovxCC9BSh/rKhuQJV5AVVC8M2fdaIdTjFyDqye+ObM0/l3/pEnNqMbz8QvLMypY6/cAVz8H9mfREI0nMUr9vDJrJw3i/CrVF6HBIOlAhxIV3lYn2hTcKSU=,iv:Ca27RNlAg6S+aIzApRk6NhrEyabn+E9oz2EERBMsHRo=,tag:bv3sIrvc5Or+lhIy5fUyJA==,type:str]
    JITSI_CLIENT_ID: ENC[AES256_GCM,data:FsLj+ugqJU0w7gVDaiQMZcZs2iwQ/Ca+eKEUjcuec2CqVER7z7Ni,iv:gI1/SpUzgjdivy0f/Uj3Nako8VvKK8ASJBRYKYfltB4=,tag:DglZpCKc5Ztnu5c7bULHsA==,type:str]
    JITSI_CLIENT_SECRET: ENC[AES256_GCM,data:qdmu6bEroM2lN45/BbefTqFjG+CeLcQFt9gK+GXZnmdm4ybjpENlG1U2UsMmDIOQ69UEtXgqPWpjK+1ggdokOxMpPTTbs9vkSI7ZwAovAa8Dic5wlNtkUHgxVcOIGflE7x3AknnS1zJmsmakOQvuVs3Gc9a/0wpBs+ag3Abm,iv:jpcI+tWn93TBNnr3E3FYCdumBrtug/FHSaXiMj9RUg8=,tag:PJzbfGDkcTlpSnrnK29SpA==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNkxTK01EV1lINHdYT2x3
            eVYwdmlsTjFOZXRmTlhNVUhvOGttZUwzeGw0CjQ1b0w4N21JQjdPenRrcWU0N3ps
            TWQvQ3VkakNpclVuOUQxam1rU0hmbXcKLS0tIDdHSmxpL21PUXZEYkcrK0FNZjBX
            VFlVNFl2TjlVQ3JlM3NxTzZwYVZadDAK7kj/kZISooDzsIr4NLkBnStwefddG2ar
            Fep4gE95HDsb+Z23hwNsM1Ew9vUzbLkKXX0v7f1tBj1NJT+mTbNCIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UTZrLzZHeWNBR0FXeTds
            a1NZV3MvaWlwTmg0VHgxNjlHUEcvN05xWm53CkcvNFkvYWswT3NuOFo0SG40MVBC
            UUxyR3Bvd3JnWHRqd0pkNzdFWVlVb0kKLS0tIE9PVUlZc1N5Sy9KS2JuNk44TzNh
            MjZraVJMQnpiODAreXNndU9zUDJabnMKYi8fxiBgMzq38HAn3eIGxfvsg1QrT1Fw
            wrL1/rQpX6VDGEOKTvaqRib22klDe90bF4L1OKwXnvOiuSFQ+pyGKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T21:41:26Z"
    mac: ENC[AES256_GCM,data:xwFe8hoOBTWo0zxzTZQ4SdXsGfpfeQIrSYry1lmvfybS6td/GbAMsg1zP8sdF1BJso6qT5JouGSTj9hQvv+PTm9o73GwKn5HNH7gbPCgPEGFe6HsJTF8oy2ZruWsECVt5ME9HgHAXmkg4mLuggRNwaudbaJ5lb8zcwL2QosXLUE=,iv:Pw8Ru9srDE3B2gzRfcq/IbTPmUMLcxIDItXIS29XsBI=,tag:lW/5SCgkIMRTHQr2dvquzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
