apiVersion: v1
kind: Secret
metadata:
    name: geoip-credentials
    namespace: authentik
type: Opaque
stringData:
    accountId: ENC[AES256_GCM,data:2G+5grOd7Q==,iv:H+B9fletM7wyeaqELY3SiF74CYg2GEgSy25OpsjKtzQ=,tag:9Q4AQ0i8JGVKEcQFCwfvHg==,type:str]
    licenseKey: ENC[AES256_GCM,data:Qk816JCJE+3g/4oCBv2XOD+ZTkYnFs/cauOid8Plf9MPKL1boZ9fMQ==,iv:uSrPv7jhgbSh28gMyoptrvsuhVFGN8LdD4LcEIgBMaA=,tag:zln0EZWi+1GnDQN4F3KYOw==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YTFpV21zMGRrNytCbkN3
            OHI5V3A4dUdoWjhxSTUvUm5QWHpKS3ZEOVFnCnlkVUt3QXMwOW81UVQ5R2VZclAw
            VzdkS2l3U3JKMnZQWjFaVE9ETzRwZGcKLS0tIFF2R0lVTFBVSnQ5V0ExVEdEaHds
            NDcrRitXQ2E1M1lvWVdkV2dDbnVSdTQK4+6oASN9Rks4wDhA+ogkhp2l1N3ZiULX
            r8BY09lVrL379a8CjfJoVS4CqE+kW+aI6d1hH8AFZ6Xwrp4aGoLTvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMjNwUDZxTWpTc3RTMENa
            Z2QzZlN3OEJaNkhkSm1JY3NTbEFMNFp5T2lZCnJHbjA2VG13UUZHbUFVME1ia2c3
            Nkhjck9WM3FKYjJ6a29XSFVYV1pKZEUKLS0tIFNQejVmRnZ5M1NLQVpXMk4vcndX
            djNITGRCaGFSamNRZnM5Vmora2kvOHcKU7pI5OvEgJWuCal9g87vDLotqhxxzIdY
            36Xw0+LR26DX/5Eq6XbdCL3B/HqYj24MoPcKePsE+gJxyzCGmBiXOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T16:31:45Z"
    mac: ENC[AES256_GCM,data:EvpOMhMdt6Ngia5vxDTDFbiXX+y/EczJQmzLjrwYaOqIVdYoLjQleo2FQUj5h7ykU5cG8vqz+v6qjMESYN9xvn2dS7KAmb3FEbmr2/Sphn9UfooJm0HXoTiLCRKUD4TV9gsHKzTTv5PUMcIOLYJlp6gxTAeUfn2ACYUxS9hvtVE=,iv:C4je2Zvw6g4oXiDXTgPw5AI9bPeN+UIN7XE6gymMXtg=,tag:uxNnnmqXaoPd1UWP1u64wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
