---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
components:
  - ../../../components/helm-configmap-reference
resources:
- authentik-secrets.sops.yaml
- geoip-credentials.sops.yaml
- helmrelease.yaml
- httproute.yaml
- namespace.yaml
- postgres-credentials.sops.yaml
- reference-grant.yaml
- ../whoami/authentik-blueprint.yaml
configMapGenerator:
- name: values
  files:
  - values.yaml=values.yaml
