---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:QbwDIQqQZ/SPQ7Y/eAgEHp/WzEXyEYCmZen+pFe6Y70bsg==,iv:L3Ox4ORnZXzB/UAkK43YTDJvwA2D9PPKxfKI1YiQhVs=,tag:Z8CRw7BVwyJfKlWW9dRnRw==,type:str]
  user-password: ENC[AES256_GCM,data:R+xg4biqBWT9QNkfHm2BF7kqrwUmKTcIWbTQhWplUfc3Mw==,iv:plK0ZfQgTEw86mjrq+VxzpkyLFP0yEn9GxYEqwbb1yM=,tag:TDMYmREF3rdD2xkT/+AC+A==,type:str]
  replication-password: ENC[AES256_GCM,data:S1zg8sWQQoGDhfVoy3+TP0e1wfoyucT8El7+n4oZKIIRwQ==,iv:M4c8bqIJkxCnlsey2dV6g1JjE1RzgnuBd6jc1FpW32c=,tag:OYR+XbK/gsVTOQSzOoPwIw==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VlNnVjBKUDFWQjJINEEy
      a2gvOG4vYUdKUHoxdUQ1M1A2RVVvTkRmRUZrCnYyaHo0R3ZZY3VsL0NrY0lzSnFT
      TVN0QnNXSGNKNGpyaktvRWZ1UUl2eTAKLS0tIEIwWjd6eWFtTFpFTVUzVlR2T1Vl
      S0Rrd1NnNkNCL3hvdmc1OENHY25OVE0KWP+lkkYPziEa0uvNpktkqGmMkk/YPXf8
      d+4KAs6yMtWmhOlWkhCHduUw56+mKegc9pCab8FgJP1JdgI4SXwbGQ==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaU5CSVBDb2c4VkFyaXV2
      TWFqL0FkYnpkL2RTcHowbzB1ZWtYMjZHSm53CjI3L2pFcnVpeHFrbW56ZkFaT2Fw
      ZDIrYkRwU3Jxdi92WTlNaldtMXdUYXcKLS0tIGNjWWZ5a3ZPVzdLRVJBL281c0d0
      UmtVVGdIaWF4NU5OTFg5bEZEV0FTVGMKfoazuurS05jZMSPqXgZUtG+6CwgX7Vd7
      9mdYb33W+TXew1LvmPxSqlfNAEAAj0VRsy7SV+uFEhtk3zalD44bFg==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T16:31:56Z"
  mac: ENC[AES256_GCM,data:l9W125+VVMYFrf15a+Zv8qPWEM5126lFxVVFJEdkauK0mDQtQnfCqypAfEmON1UUgFiv4z0NpxGdHb6sfYEcapy22PtS8ipGInwQYR96szQ46eYttrX6RUqRB+bYu5hjFNMr44TlN3gR6YW3KmQCoZvHNHtfoODY60o3D5i92XI=,iv:wUTp35b4RHkMD0mhrMZM+BzMLK1kCaj4j4iXzjrVki8=,tag:KnbbcB2Eue8690RrFRiFiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
