---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:Nc9dI9zDeJbyLqHToLVXt0eKm6nRdoiy9E++A+B1OVR4Lo4cBK+kPdB0AsKYr3U4,iv:bt35m+tJ2ygpVjz4unZRpczGZBrVuAdhKi2JjhmcYrQ=,tag:kxKeTzoJhTKxsDz+UWUGGw==,type:str]
  user-password: ENC[AES256_GCM,data:t2jIEAx9Np5FpGtBObXwIRUc4iqkeK2qTIIzm8NUh5fWqL5juBnMgk5fEWVOZUyo,iv:UEptqDoq8vcm/m7vhU044utXNUI38Sseub7407/85DQ=,tag:3Xsqh9K3cr1led7Q9igtSg==,type:str]
  replication-password: ENC[AES256_GCM,data:dEvmRyCtcrwFyFWuawURFY5axeSISy2ngqtoDXpyJFYkDYyeCt6oAG30iE/kDXUa,iv:5TpVfPlEwvTBRr4iSljcbWkq+UfK9a8jIKL0l41qztc=,tag:RcKbBEu6tDKFUA9JGuji5w==,type:str]
sops:
  age:
  - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTXJTa05BOGg5ZVdhM3VY
      MWRIM3d5eUtMNXl3RS9KQ1ViWFpWZmpPWXlZCkJlbVQvNStXQ2lzQ04rOTFDeWJY
      SGVxVGJsYzMvTnI3V01tZmRHNUVoZGMKLS0tIEVNSnZTdXpkV2xOV3N6WEtMSURB
      VjNGR0VUZ1Jla2dmM3lyRmFmMzRWMm8KzvGz2mFzPJsFd628m42tNR4RqGIkxHRY
      Hn4PFGvIeIJ4jT4/+QqRnYHPiv/YwBpFFeEiBzT3SX25erVgVt+mKA==
      -----END AGE ENCRYPTED FILE-----
  - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUjdCUE84RUZ6ZzlMei9m
      MlZRODNINVFtcHBEZjlrRHlRZ1lJbEZGelhFCjl2alhwVG9PTUR0YjljTXBmZEc4
      ZUUveTR4OGZmc1NwbGI1c2NmdEhweWsKLS0tIDdOMW1XY2JsUFZhQUFteFM0WmhX
      UWRFZFRNMlM0M0xaK3lHekRvdWpBL00K2919iLha9l6uFfuKGTn9WTX9vSzDMMga
      ynOPGfJi5Bkxld/5oDU+Rh4nK9BdTeLGIN0ILF4T9ylrPB7AesRlMQ==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T16:45:40Z"
  mac: ENC[AES256_GCM,data:amYJup2N/QmnmI+Zhs8MQyvK6MuYzuMVw+CQ/bK5jOiZujLS/3LDiN/V6EAeyhX/YpZufvnx/HAyTOkiRcn+VLKRwJjZ4vCOyB4yGw8lY5hPNTHHUc2KvU4AAAdIQbucnC5+HmKHECi3sz5vnPFLsctbZ/iVP0OUbxvvpB+IUg0=,iv:lWFSU4ZQFDJm5RNpkDdcwGMSn3rN6R5rv+bojfHL5Xc=,tag:2Zm9+UWteZiUCwj9z4FeBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
