apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:ZNqvRbdT6EIqoGQqpXSR94ZhG7vcfa3B5xzwL5Vx5+3+fGJ92bl32tt7cneTEvy0,iv:bt35m+tJ2ygpVjz4unZRpczGZBrVuAdhKi2JjhmcYrQ=,tag:Hrv6xDuxPsNfvZ9ic1qR8A==,type:str]
    user-password: ENC[AES256_GCM,data:MOMRy3NRO+xcWr9/CpjHg0lhXKrJML85j8gwNOuvij3XxphCcQrRo5aZkEABL+Re,iv:UEptqDoq8vcm/m7vhU044utXNUI38Sseub7407/85DQ=,tag:4qA1RrTzEVz4+XaMlGFpRg==,type:str]
    replication-password: ENC[AES256_GCM,data:U7sVX8GQssxbY9P9nfCf5oRWrclyTDP+QzWW7BeSTZcxa6w4MACdQRMEIQr5AdVs,iv:5TpVfPlEwvTBRr4iSljcbWkq+UfK9a8jIKL0l41qztc=,tag:g59HES2WoR9IE5j41eYN8Q==,type:str]
sops:
    age:
        - recipient: age1k7qp72hl0zfc4z7cg4xue7evstnq33c9855s6p4u3rfsyk353q8qvcze5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdnVma05uclhDNXpVOTcv
            RUtMemM2SFhjVlJNb0hmZHpkSGpUY1BkY0Y4CitGK3p0cDk4V3VDMHQ3TWFrTUZw
            bUNqUEtJS0dyY0t4OGVMbmcrWUd0YTQKLS0tIEI5Zjc0ZFFJRnFPNmZobUtOQXlH
            RjlqZGRNdmJLa09obTBHK3VwODZpZTQKqiX5qoPkcG4fYA6FpojpCYDRzatZciwU
            bZt4DkVE0DFelikGviqtZGrxzSE5HgXf2uq1NR+/WWLvbKE1B/CVYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y55epapn8p7yark3wjjfqyqnl842lyn5xxlr7m7cdfchua5ctfgs8rnv0d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UFNYTGtCWExxdFIraGVj
            M2dLZFZicVc3eW1KQlMyU2VIZDFpeUFBZjMwCk9uNUtoTkFFRHUwcE53M2VUWU9F
            SkhJWWlFMW50YU5OT3Q0bnpISS9PWU0KLS0tIEdidTlkMTdMVS9WRVJHVXNIVzlX
            UGk5K0JjN1lmdkZDNk1IcW91dkF4MlkKgBaWZyGuhWH3LgWyIyCB+nEQew71OfB/
            xF9elI7FjJM+v85gkdfCTSe+dHgv9V26f1Hrp8vjoB9DFaCtjkdlYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T18:17:27Z"
    mac: ENC[AES256_GCM,data:EB2nzgKkLjqKkbSkNnwc8rC6TRD1cHHEKjPudX8nFxXWEjoDcVmL2Hj6Nk4jjMflQypZClQCVqeyYNgbIg8c0PpGj3YBRGWroNP6oL23b6K/nzBHR0QyM8H54raoWnrD81fntDh/dkuYPzWamYK9uAFBt2gN4sqTv7wncnh9w8I=,iv:pcIhrZZNRnIbUTTfxnmxacNQdzhnuaVkxUL+mDy/I+Y=,tag:+DAOHwtsS+tNN0tZ5KLT8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
