---
global:
  envFrom:
  - secretRef:
      name: authentik-secrets
authentik:
  postgresql:
    password: file:///mnt/secrets/postgresql/user-password
geoip:
  enabled: true
  existingSecret:
    secretName: geoip-credentials
    accountId: accountId
    licenseKey: licenseKey
postgresql:
  enabled: true
  auth:
    existingSecret: postgres-credentials
    secretKeys:
      adminPasswordKey: "aa8e959560bbb14ca15eae7416f96dfcd03b28194c050b58"
      userPasswordKey: "7a69c70115766b95e7c1b513bce3c5a1d8f1a4a6399542e4"
      replicationPasswordKey: "18ddb87be5d68bb9ee1b62a2e6f9cb4df8742601a613d35d"
prometheus:
  rules:
    enabled: true
redis:
  enabled: true
server: &common-server-settings
  volumes:
  - name: postgres-creds
    secret:
      secretName: postgres-credentials
  - name: authentik-secrets
    secret:
      secretName: authentik-secrets
  volumeMounts:
  - name: postgres-creds
    mountPath: /mnt/secrets/postgresql
    readOnly: true
  - name: authentik-secrets
    mountPath: /mnt/secrets/authentik
    readOnly: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
worker: *common-server-settings
