---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jens@plueddemann.de
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - selector:
        dnsNames:
        - "sso.jfp.one"
      http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: jfp-one
            kind: Gateway
            namespace: networking
            sectionName: authentik-http
    - selector:
        dnsNames:
        - "jfp.one"
      http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: jfp-one
            kind: Gateway
            namespace: networking
            sectionName: http
    - selector:
        dnsNames:
        - "talk.jfp.one"
      http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: jfp-one
            kind: Gateway
            namespace: networking
            sectionName: jitsi-http
